#!/bin/bash

TARGET=${1:-x86_64}
shift

./env/configure $TARGET
./env/build $TARGET
qemu-system-$TARGET -name "Leaf $TARGET" -drive file="release/Leaf-$TARGET-$(date +%B-%Y).iso",index=0,format=raw "$@"