#!/bin/bash

target_arch=${1:-x86_64}
bootloader=${2:-limine}

if [ ! -d "build-$target_arch-$bootloader" ]; then
    echo ""build-$target_arch-$bootloader" Doest exist! You have to configure the kernel before building! Use ./env/configure <target> <bootloader> <toolchain> (These options are optional!)."
    exit
fi

pushd "build-$target_arch-$bootloader"
make
popd

pushd "arch/$target_arch"
./gen-$bootloader.sh
popd
echo "Finished building. Enjoy!"